name: handyman_bbk_panel
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  geocoding: ^3.0.0
  geolocator: ^13.0.4
  google_sign_in: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  intl: ^0.20.2
  lottie: ^3.3.1
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.17
  sign_in_with_apple: ^7.0.1
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  flutter_rating_bar: ^4.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/

 